"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeSanitize from "rehype-sanitize";
import { ArrowUp, Bot, Brain, CircleStop, FileText, Globe2, Pencil, Plus, RefreshCw, Sparkles, Trash2, WifiOff } from "lucide-react";
import { ErrorState, Loading } from "@/components/ui";
import { api, errorMessage } from "@/features/items/api";
import { useWorkspace } from "@/components/workspace-context";
import "./assistant.css";

type Source={id:string;citation:string;title:string;type:string;excerpt:string;href:string;sourceKind?:"SYNAPSE"|"WEB"}; type Message={id:string;role:"USER"|"ASSISTANT";content:string;sources?:Source[]|null;createdAt:string}; type Conversation={id:string;title:string;webSearchEnabled:boolean;reasoningEnabled:boolean;messages?:Message[]}; type Status={state:"disabled"|"offline"|"model_missing"|"ready";reasoningAvailable:boolean;web:{enabled:boolean;reachable:boolean}}; type Phase="preparing"|"searching_knowledge"|"searching_web"|"generating"|"reasoning";
const phaseText:Record<Phase,string>={preparing:"Preparo la risposta...",searching_knowledge:"Cerco nelle tue conoscenze...",searching_web:"Cerco sul Web...",generating:"Sto preparando la risposta...",reasoning:"Sto ragionando..."};
function Markdown({content,sources=[]}:{content:string;sources?:Source[]}){const map=new Map(sources.map(s=>[s.citation,s]));const safe=content.replace(/\[S\d+\]/g,c=>map.has(c)?`[${c}](${map.get(c)!.href})`:"[fonte non verificata]");return <div className="assistant-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} components={{a:({href,children})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>}}>{safe}</ReactMarkdown></div>}
function Sources({sources,kind}:{sources:Source[];kind:"SYNAPSE"|"WEB"}){const list=sources.filter(s=>(s.sourceKind??"SYNAPSE")===kind);if(!list.length)return null;return <section className="assistant-sources"><strong>{kind==="WEB"?"Fonti Web":"Fonti Synapse"}</strong>{list.map(s=><Link href={s.href} key={s.id} target={kind==="WEB"?"_blank":undefined} rel={kind==="WEB"?"noopener noreferrer":undefined}><FileText size={14}/><span><b>{s.citation} · {s.title}</b><small>{s.type} · {s.excerpt}</small></span></Link>)}</section>}
function Pending({phase}:{phase:Phase}){return <div className="assistant-pending" aria-live="polite"><p>{phaseText[phase]} <i aria-hidden="true"/></p></div>}
export function Assistant(){const{notify}=useWorkspace();const[status,setStatus]=useState<Status|null>(null),[list,setList]=useState<Conversation[]>([]),[current,setCurrent]=useState<Conversation|null>(null),[text,setText]=useState(""),[web,setWeb]=useState(true),[reasoning,setReasoning]=useState(false),[phase,setPhase]=useState<Phase|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const controller=useRef<AbortController|null>(null);const available=status?.state==="ready",webAvailable=!!(status?.web.enabled&&status.web.reachable);
const refresh=async()=>{const[s,c]=await Promise.all([api<Status>("/api/ai/status"),api<{conversations:Conversation[]}>("/api/ai/conversations")]);setStatus(s);setList(c.conversations);return c.conversations};const load=async(id:string)=>{const r=await api<{conversation:Conversation}>(`/api/ai/conversations/${id}`);setCurrent(r.conversation);setWeb(r.conversation.webSearchEnabled);setReasoning(r.conversation.reasoningEnabled);setPhase(null)};useEffect(()=>{void refresh().then(x=>x[0]&&load(x[0].id)).catch(e=>setError(errorMessage(e)))},[]);
const create=async(trigger?:unknown)=>{if(trigger===undefined){const remaining=list.filter(c=>c.id!==current?.id);setList(remaining);setCurrent(null);if(remaining[0])void load(remaining[0].id);return}try{const r=await api<{conversation:Conversation}>("/api/ai/conversations",{method:"POST",body:JSON.stringify({mode:"AUTO",webSearch:webAvailable,reasoning:false})});setList(x=>[r.conversation,...x]);setCurrent({...r.conversation,messages:[]});setWeb(r.conversation.webSearchEnabled);setReasoning(false)}catch(e){setError(errorMessage(e))}};const preferences=async(w:boolean,r:boolean)=>{if(!current)return;setWeb(w);setReasoning(r);await api(`/api/ai/conversations/${current.id}`,{method:"PATCH",body:JSON.stringify({webSearch:w,reasoning:r})}).catch(e=>notify(errorMessage(e)))};
useEffect(()=>{const actions=document.querySelector(".assistant-chat-head > div:last-child");if(!actions||!current)return;const existing=actions.querySelector("[data-rename-chat]");if(existing)return;const button=document.createElement("button");button.type="button";button.className="icon-button";button.dataset.renameChat="true";button.setAttribute("aria-label","Rinomina conversazione");button.textContent="✎";button.onclick=async()=>{const title=window.prompt("Nome della conversazione",current.title)?.trim();if(!title)return;try{await api(`/api/ai/conversations/${current.id}`,{method:"PATCH",body:JSON.stringify({title})});setCurrent(value=>value?{...value,title}:value);setList(items=>items.map(item=>item.id===current.id?{...item,title}:item))}catch(cause){setError(errorMessage(cause))}};actions.prepend(button);return()=>button.remove()},[current?.id,current?.title]);
async function send(e?:FormEvent){e?.preventDefault();if(!current||!text.trim()||busy||!available)return;const id=current.id,answer=`pending-${Date.now()}`,question=text.trim();setCurrent({...current,messages:[...(current.messages??[]),{id:`user-${Date.now()}`,role:"USER",content:question,createdAt:new Date().toISOString()},{id:answer,role:"ASSISTANT",content:"",createdAt:new Date().toISOString()}]});setText("");setBusy(true);setPhase("preparing");const abort=new AbortController();controller.current=abort;try{const res=await fetch("/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:id,message:question,webSearch:web,reasoning}),signal:abort.signal});if(!res.ok||!res.body)throw new Error("Risposta AI non disponibile.");const reader=res.body.getReader(),decoder=new TextDecoder();let buf="",out="",sources:Source[]=[];for(;;){const chunk=await reader.read();if(chunk.done)break;buf+=decoder.decode(chunk.value,{stream:true});const events=buf.split("\n\n");buf=events.pop()??"";for(const raw of events){const d=JSON.parse(raw.replace(/^data:\s*/,"")) as{type:string;token?:string;phase?:Phase;sources?:Source[];error?:string};if(d.type==="status"&&d.phase)setPhase(d.phase);if(d.type==="token"){out+=d.token??"";if(out)setPhase(null);setCurrent(v=>v?.id===id?{...v,messages:(v.messages??[]).map(m=>m.id===answer?{...m,content:out}:m)}:v)}if(d.type==="done")sources=d.sources??[];if(d.type==="error")throw new Error(d.error)}}setCurrent(v=>v?.id===id?{...v,messages:(v.messages??[]).map(m=>m.id===answer?{...m,content:out,sources}:m)}:v);void refresh()}catch(e){if((e as Error).name!=="AbortError")setError(errorMessage(e))}finally{setBusy(false);setPhase(null);controller.current=null}}
if(!status)return <Loading label="Carico l’assistente..."/>;if(error&&!current)return <ErrorState message={error} retry={()=>void refresh()}/>;return <div className="page assistant-page"><header className="page-header"><div><p className="eyebrow">Conoscenza locale, sempre privata</p><h1>Assistente AI</h1></div><span className={`ai-status ${status.state}`}><span/>{available?"Disponibile":"Non disponibile"}</span></header><div className="assistant-layout"><aside className="assistant-history"><button className="button button-primary" onClick={create}><Plus size={16}/>Nuova chat</button><div className="assistant-history-list">{list.map(c=><button key={c.id} className={current?.id===c.id?"active":""} onClick={()=>void load(c.id)}><Sparkles size={14}/><strong>{c.title}</strong></button>)}</div></aside><section className="assistant-chat">{!current?<div className="assistant-empty"><Bot size={32}/><h2>Inizia una chat</h2></div>:<><div className="assistant-chat-head"><div><h2>{current.title}</h2></div><div><button className="icon-button" onClick={()=>void api(`/api/ai/conversations/${current.id}`,{method:"DELETE",body:"{}"}).then(()=>create())}><Trash2 size={15}/></button></div></div><div className="assistant-messages">{(current.messages??[]).map(m=><article key={m.id} className={`assistant-message ${m.role.toLowerCase()}`}><span>{m.role==="USER"?"Tu":"Synapse"}</span>{m.role==="ASSISTANT"&&!m.content&&busy?<Pending phase={phase??"preparing"}/>:m.role==="ASSISTANT"?<><Markdown content={m.content} sources={m.sources??[]}/><Sources sources={m.sources??[]} kind="SYNAPSE"/><Sources sources={m.sources??[]} kind="WEB"/></>:<p>{m.content}</p>}</article>)}</div>{error&&<p className="form-error">{error}</p>}<form className="assistant-composer" onSubmit={send}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Chiedi a Synapse..." disabled={busy}/><div className="assistant-composer-actions"><div className="assistant-toggles"><label className="assistant-think-toggle"><Globe2 size={14}/><span>Ricerca Web</span><input type="checkbox" role="switch" checked={web} onChange={e=>void preferences(e.target.checked,reasoning)} disabled={busy||!webAvailable}/></label><label className="assistant-think-toggle"><Brain size={14}/><span>Ragionamento</span><input type="checkbox" role="switch" checked={reasoning} onChange={e=>void preferences(web,e.target.checked)} disabled={busy||!status.reasoningAvailable}/></label></div>{busy?<button type="button" className="button button-secondary" onClick={()=>controller.current?.abort()}><CircleStop size={15}/></button>:<button className="button button-primary" disabled={!text.trim()}><ArrowUp size={16}/></button>}</div></form></>}</section></div></div>}
