"use client";

import { useEffect, useState } from "react";
import { Bell, ChevronRight, Palette, Trash2 } from "lucide-react";
import type { PlannerCategorySummary } from "@/domain/types";
import { CategoryManager } from "@/features/planner/planner";
import { useRemote } from "@/features/items/use-remote";
import { api, changed, errorMessage } from "@/features/items/api";
import { AppSelect } from "@/components/select";
import "./settings.css";

type CategoriesResponse = { categories: PlannerCategorySummary[] };
type Preferences = { trashRetentionDays: number; timezone: string; remindersEnabled: boolean; browserNotificationsEnabled: boolean; defaultReminderTime: string; weeklyReviewDay: number; weeklyReviewTime: string; quietHoursStart: string | null; quietHoursEnd: string | null };
type SettingsResponse = { settings: Preferences; expiredOperations: number };
const retention = [7, 14, 30, 60, 90];
const weekdays = ["Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica"];

export function SettingsPage() {
  const { data, loading, error, reload } = useRemote<CategoriesResponse>("/api/planner/categories");
  const { data: settings, reload: reloadSettings } = useRemote<SettingsResponse>("/api/settings");
  const [categoriesOpen, setCategoriesOpen] = useState(false); const [nextDays, setNextDays] = useState<number | null>(null); const [preferences, setPreferences] = useState<Preferences | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (settings && nextDays === null) setNextDays(settings.settings.trashRetentionDays); if (settings && !preferences) setPreferences(settings.settings); }, [settings, nextDays, preferences]);
  async function saveRetention(confirm = false) { if (!nextDays) return; setSaving(true); setMessage(""); try { await api("/api/settings", { method: "PATCH", body: JSON.stringify({ trashRetentionDays: nextDays, confirmed: confirm }) }); setMessage("Conservazione del Cestino aggiornata."); await reloadSettings(); } catch (reason) { const status = reason as { status?: number }; setMessage(status.status === 409 ? "Alcuni gruppi nel Cestino risultano già scaduti con questo periodo. Conferma per applicare la modifica." : errorMessage(reason)); } finally { setSaving(false); } }
  async function savePreferences() { if (!preferences) return; setSaving(true); setMessage(""); try { const result = await api<SettingsResponse>("/api/settings", { method: "PATCH", body: JSON.stringify(preferences) }); setPreferences(result.settings); setMessage("Preferenze per promemoria e revisione aggiornate."); await reloadSettings(); } catch (reason) { setMessage(errorMessage(reason)); } finally { setSaving(false); } }
  const updatePreference = <K extends keyof Preferences>(key: K, value: Preferences[K]) => setPreferences((current) => current ? { ...current, [key]: value } : current);
  return <div className="page settings-page"><header className="settings-header"><div><p className="eyebrow">Il tuo spazio, le tue regole</p><h1>Configurazione</h1><p>Personalizza le categorie, i promemoria e le regole di conservazione di Synapse.</p></div></header>
    <section className="settings-section" id="categorie" aria-labelledby="categorie-heading"><div className="settings-section-heading"><div className="settings-icon"><Palette size={19} /></div><div><h2 id="categorie-heading">Categorie</h2><p>Crea e organizza i gruppi che usi per classificare le tue cose.</p></div></div><button className="settings-card" onClick={() => setCategoriesOpen(true)}><span className="settings-card-icon"><Palette size={18} /></span><span><strong>Categorie</strong><small>{loading ? "Caricamento…" : error ? "Impossibile caricare le categorie" : `${data?.categories.length ?? 0} categorie disponibili`}</small></span><ChevronRight size={18} /></button></section>
    <section className="settings-section" aria-labelledby="reminders-heading"><div className="settings-section-heading"><div className="settings-icon"><Bell size={19} /></div><div><h2 id="reminders-heading">Promemoria e revisione</h2><p>Scegli quando Synapse può richiamare la tua attenzione e il momento della revisione settimanale.</p></div></div>{preferences && <div className="settings-card settings-preferences"><div className="settings-switches"><label className="settings-switch"><span><strong>Promemoria in Synapse</strong><small>Mostra gli avvisi nella pagina Notifiche.</small></span><input type="checkbox" role="switch" checked={preferences.remindersEnabled} onChange={(event) => updatePreference("remindersEnabled", event.target.checked)} /></label><label className="settings-switch"><span><strong>Notifiche del browser</strong><small>Usa il browser se hai concesso il permesso.</small></span><input type="checkbox" role="switch" checked={preferences.browserNotificationsEnabled} onChange={(event) => updatePreference("browserNotificationsEnabled", event.target.checked)} /></label></div><div className="settings-form-grid"><label>Fuso orario<input value={preferences.timezone} onChange={(event) => updatePreference("timezone", event.target.value)} placeholder="Europe/Rome" /></label><label>Ora predefinita<input type="time" value={preferences.defaultReminderTime} onChange={(event) => updatePreference("defaultReminderTime", event.target.value)} /></label><label>Revisione settimanale<AppSelect aria-label="Giorno della revisione" value={String(preferences.weeklyReviewDay)} onValueChange={(value) => updatePreference("weeklyReviewDay", Number(value))} options={weekdays.map((day, index) => ({ value: String(index + 1), label: day }))} /></label><label>Ora revisione<input type="time" value={preferences.weeklyReviewTime} onChange={(event) => updatePreference("weeklyReviewTime", event.target.value)} /></label></div><div className="dialog-footer"><button className="button button-primary" disabled={saving} onClick={() => void savePreferences()}>{saving ? "Salvataggio…" : "Salva preferenze"}</button></div></div>}</section>
    <section className="settings-section" aria-labelledby="trash-heading"><div className="settings-section-heading"><div className="settings-icon"><Trash2 size={19} /></div><div><h2 id="trash-heading">Conservazione del Cestino</h2><p>Gli elementi presenti nel Cestino vengono eliminati definitivamente dopo il periodo selezionato.</p></div></div><div className="settings-card settings-retention"><label>Periodo di conservazione<AppSelect aria-label="Periodo di conservazione" value={String(nextDays ?? 30)} onValueChange={(value) => setNextDays(Number(value))} options={retention.map((days) => ({ value: String(days), label: `${days} giorni` }))} /></label><button className="button button-primary" disabled={saving || nextDays === settings?.settings.trashRetentionDays} onClick={() => void saveRetention()}>{saving ? "Salvataggio…" : "Salva"}</button></div>{message && <div className="settings-notice" role="status"><p>{message}</p>{message.includes("Conferma") && <button className="button button-danger compact" disabled={saving} onClick={() => void saveRetention(true)}>Conferma modifica</button>}</div>}</section>
    {categoriesOpen && data && <CategoryManager categories={data.categories} onClose={() => setCategoriesOpen(false)} onChanged={() => { changed(); reload(); }} />}
  </div>;
}
