"use client";
import Link from "next/link";
import { useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { useRemote } from "@/features/items/use-remote";
import { api } from "@/features/items/api";
import { getItemHref } from "@/domain/item-url";
import "@/features/notifications/notifications.css";
type Item={id:string;itemKey:string|null;title:string}; type Data={completed:number;inbox:number;overdue:Item[];upcoming:Item[];inactive:Item[];review:{notes:string;completedAt:string|null}};
export function WeeklyReviewPage(){const {data,reload}=useRemote<Data>("/api/weekly-review");const [notes,setNotes]=useState(""); if(!data)return <div className="page weekly-review-page">Caricamento…</div>; const save=async(done:boolean)=>{await api("/api/weekly-review",{method:"PATCH",body:JSON.stringify({notes,completed:done})});reload()}; const list=(title:string,items:Item[],description:string) => <section className="review-card"><div><h2>{title}</h2><p>{description}</p></div>{items.length?<div className="review-items">{items.map(i=><Link key={i.id} href={getItemHref(i as never)}><span>{i.itemKey}</span>{i.title}</Link>)}</div>:<p className="detail-empty">Tutto in ordine.</p>}</section>;return <div className="page weekly-review-page"><header className="notification-header"><div><p className="eyebrow">Metti in ordine la settimana</p><h1>Revisione settimanale</h1><p>Un momento per chiudere il passato e definire il prossimo passo.</p></div><div className="review-stats"><strong>{data.completed}</strong><span>completate</span><strong>{data.inbox}</strong><span>da organizzare</span></div></header><div className="review-grid">{list("Attività scadute",data.overdue,"Rimetti in movimento ciò che è rimasto indietro.")}{list("In scadenza",data.upcoming,"Proteggi il tempo per le prossime priorità.")}{list("Progetti da riprendere",data.inactive,"Progetti attivi senza un aggiornamento recente.")}</div><section className="review-card review-notes"><div><h2>Decisioni della settimana</h2><p>Annota le priorità e i passi concreti che vuoi portare avanti.</p></div><textarea rows={7} value={notes||data.review.notes} onChange={e=>setNotes(e.target.value)} placeholder="Scrivi le priorità e le decisioni…"/><div className="dialog-footer"><button className="button button-secondary" onClick={()=>void save(false)}>Salva note</button><button className="button button-primary" onClick={()=>void save(true)}><CheckCircle2 size={15}/> Completa revisione</button></div></section></div>}
