"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Copy, Focus, ListTodo, Pause, Play, Plus, Save, Sparkles, Trash2, X } from "lucide-react";
import type { PlannerData, TimeBlockCategory, TimeBlockSummary } from "@/domain/types";
import { getItemHref } from "@/domain/item-url";
import { Modal } from "@/components/ui";
import { api, changed, errorMessage } from "@/features/items/api";
import { useRemote } from "@/features/items/use-remote";
import { useWorkspace } from "@/components/workspace-context";
import "./planner.css";

const categoryLabels: Record<TimeBlockCategory, string> = { WORK: "Lavoro", STUDY: "Studio", TRAINING: "Allenamento", BREAK: "Pausa", PERSONAL: "Personale", OTHER: "Altro" };
const localDate = (date: Date) => new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Rome" }).format(date);
const startOfWeek = (date: Date) => { const result = new Date(`${localDate(date)}T00:00:00`); result.setDate(result.getDate() - ((result.getDay() + 6) % 7)); return result; };
const dateAt = (date: string, hour: number) => `${date}T${String(hour).padStart(2, "0")}:00`;
const formatTime = (value: string) => new Intl.DateTimeFormat("it-IT", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "Europe/Rome" }).format(new Date(value));
const formatDate = (value: string) => new Intl.DateTimeFormat("it-IT", { weekday: "long", day: "numeric", month: "long", timeZone: "Europe/Rome" }).format(new Date(`${value}T12:00:00`));
const inputValue = (value: string) => { const d = new Date(value); return `${localDate(d)}T${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`; };

export function Planner({ initialView = "day" }: { initialView?: "day" | "week" }) {
  const [view, setView] = useState<"day" | "week">(initialView); const [selected, setSelected] = useState(() => localDate(new Date()));
  const [editor, setEditor] = useState<TimeBlockSummary | "new" | null>(null); const [seed, setSeed] = useState<{ itemId?: string; title?: string } | null>(null); const [focus, setFocus] = useState<TimeBlockSummary | null>(null);
  const range = useMemo(() => { const origin = view === "week" ? startOfWeek(new Date(`${selected}T12:00:00`)) : new Date(`${selected}T00:00:00`); const end = new Date(origin); end.setDate(end.getDate() + (view === "week" ? 7 : 1)); return { from: origin.toISOString(), to: end.toISOString(), origin }; }, [selected, view]);
  const { data, loading, error, reload } = useRemote<PlannerData>(`/api/planner?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`);
  const move = (offset: number) => { const value = new Date(`${selected}T12:00:00`); value.setDate(value.getDate() + offset * (view === "week" ? 7 : 1)); setSelected(localDate(value)); };
  const openNew = (hour = 9, item?: { id: string; title: string }) => { setSeed(item ? { itemId: item.id, title: item.title } : null); setEditor("new"); if (hour !== 9) setSeed({ ...(item ?? {}), title: item?.title }); };
  const days = Array.from({ length: view === "week" ? 7 : 1 }, (_, index) => { const day = new Date(range.origin); day.setDate(day.getDate() + index); return localDate(day); });
  return <div className="page planner-page">
    <header className="planner-header"><div><p className="eyebrow">Pianificazione personale</p><h1>Planner</h1><p>Organizza il tempo che vuoi dedicare alle idee che contano.</p></div><div className="planner-top-actions"><Link href={view === "week" ? "/planner" : "/planner/week"} className="button button-secondary"><CalendarDays size={15}/>{view === "week" ? "Giorno" : "Settimana"}</Link><button className="button button-primary" onClick={() => openNew()}><Plus size={16}/>Nuovo blocco</button></div></header>
    <div className="planner-toolbar"><div className="planner-nav"><button className="icon-button" aria-label="Periodo precedente" onClick={() => move(-1)}><ChevronLeft size={18}/></button><button className="planner-date-button" onClick={() => setSelected(localDate(new Date()))}>{view === "week" ? `Settimana del ${formatDate(days[0])}` : formatDate(selected)}</button><button className="icon-button" aria-label="Periodo successivo" onClick={() => move(1)}><ChevronRight size={18}/></button></div><button className="button button-ghost compact" onClick={() => setSelected(localDate(new Date()))}>Oggi</button></div>
    {error ? <div className="error-banner">{error} <button className="text-link" onClick={reload}>Riprova</button></div> : loading && !data ? <div className="planner-loading">Caricamento del piano…</div> : data && <>
      <section className="planner-summary" aria-label="Riepilogo del tempo pianificato">{Object.entries(data.summary).filter(([, value]) => value.planned || value.actual).map(([category, value]) => <div key={category}><span className={`planner-dot category-${category}`}/><strong>{categoryLabels[category as TimeBlockCategory]}</strong><small>{hours(value.planned)} pianificate · {hours(value.actual)} registrate</small></div>)}{!Object.values(data.summary).some((value) => value.planned) && <p>Inizia con un blocco: il tuo piano resterà collegato al resto di Synapse.</p>}</section>
      <div className="planner-layout"><section className="planner-calendar" aria-label={view === "week" ? "Calendario settimanale" : "Agenda giornaliera"}>{view === "week" ? <WeekGrid days={days} blocks={data.blocks} onSelectDay={(day) => { setSelected(day); setView("day"); }} onEdit={setEditor} onNew={(day, hour) => { setSelected(day); openNew(hour); }} /> : <DayTimeline day={selected} blocks={data.blocks} onEdit={setEditor} onNew={openNew} />}</section><aside className="planner-side"><Tasks tasks={data.tasks} onSchedule={(task) => { setSeed({ itemId: task.id, title: task.title }); setEditor("new"); }}/><Templates templates={data.templates} day={selected} onApplied={() => { changed(); reload(); }} /></aside></div>
    </>}
    {editor && <BlockEditor block={editor === "new" ? null : editor} day={selected} seed={seed} onClose={() => { setEditor(null); setSeed(null); }} onSaved={() => { changed(); reload(); setEditor(null); setSeed(null); }} onFocus={setFocus}/>} {focus && <FocusMode block={focus} onClose={() => setFocus(null)} onSaved={() => { changed(); reload(); }} />}
  </div>;
}

function DayTimeline({ day, blocks, onEdit, onNew }: { day: string; blocks: TimeBlockSummary[]; onEdit: (block: TimeBlockSummary) => void; onNew: (hour?: number) => void }) { const hours = Array.from({ length: 24 }, (_, hour) => hour); return <div className="timeline"><div className="timeline-heading"><span>Orario</span><span>{formatDate(day)}</span></div>{hours.map((hour) => { const at = new Date(`${day}T${String(hour).padStart(2, "0")}:00`).getTime(); const hourBlocks = blocks.filter((block) => new Date(block.startsAt).getTime() >= at && new Date(block.startsAt).getTime() < at + 3_600_000); return <div className="timeline-hour" key={hour}><time>{String(hour).padStart(2, "0")}:00</time><div className="timeline-slot"><button aria-label={`Aggiungi un blocco alle ${hour}:00`} className="timeline-add" onClick={() => onNew(hour)}><Plus size={14}/></button>{hourBlocks.map((block) => <BlockCard block={block} key={block.id} onClick={() => onEdit(block)}/>)}</div></div>; })}</div>; }
function WeekGrid({ days, blocks, onSelectDay, onEdit, onNew }: { days: string[]; blocks: TimeBlockSummary[]; onSelectDay: (day: string) => void; onEdit: (block: TimeBlockSummary) => void; onNew: (day: string, hour: number) => void }) { return <div className="week-grid"><div className="week-head"><span/> {days.map((day) => <button key={day} onClick={() => onSelectDay(day)}><strong>{new Intl.DateTimeFormat("it-IT", { weekday: "short" }).format(new Date(`${day}T12:00:00`))}</strong><span>{new Date(`${day}T12:00:00`).getDate()}</span></button>)}</div>{Array.from({ length: 24 }, (_, hour) => hour).map((hour) => <div className="week-row" key={hour}><time>{String(hour).padStart(2, "0")}</time>{days.map((day) => <div className="week-slot" key={day}><button className="week-add" aria-label={`Aggiungi un blocco il ${day} alle ${hour}`} onClick={() => onNew(day, hour)}><Plus size={12}/></button>{blocks.filter((block) => block.startsAt.startsWith(day) && new Date(block.startsAt).getHours() === hour).map((block) => <BlockCard block={block} key={block.id} compact onClick={() => onEdit(block)}/>)}</div>)}</div>)}</div>; }
function BlockCard({ block, onClick, compact = false }: { block: TimeBlockSummary; onClick: () => void; compact?: boolean }) { return <button className={`time-block category-${block.category} ${block.status.toLowerCase()} ${compact ? "compact-block" : ""}`} onClick={onClick} title={`${block.title}, ${formatTime(block.startsAt)}–${formatTime(block.endsAt)}`}><span className="time-block-time">{formatTime(block.startsAt)}–{formatTime(block.endsAt)}</span><strong>{block.title}</strong>{!compact && <span className="time-block-meta">{categoryLabels[block.category]}{block.item && ` · ${block.item.title}`}{block.conflict && " · Sovrapposto"}</span>}</button>; }
function Tasks({ tasks, onSchedule }: { tasks: PlannerData["tasks"]; onSchedule: (task: PlannerData["tasks"][number]) => void }) { return <section className="planner-panel"><div className="panel-title"><ListTodo size={16}/><h2>Attività aperte</h2></div>{tasks.length ? tasks.map((task) => <div className="planner-task" key={task.id}><Link href={getItemHref(task)}>{task.title}</Link><small>{task.dueAt ? `Scade ${new Intl.DateTimeFormat("it-IT", { day: "numeric", month: "short" }).format(new Date(task.dueAt))}` : "Senza scadenza"}</small><button className="text-link" onClick={() => onSchedule(task)}>Pianifica</button></div>) : <p className="muted">Non ci sono attività aperte.</p>}</section>; }
function Templates({ templates, day, onApplied }: { templates: PlannerData["templates"]; day: string; onApplied: () => void }) { const { notify } = useWorkspace(); async function apply(template: PlannerData["templates"][number]) { const blocks = Array.isArray(template.blocks) ? template.blocks : []; const confirmed = window.confirm(`Applicare “${template.name}” a ${formatDate(day)}? I blocchi esistenti non verranno modificati.`); if (!confirmed) return; try { await Promise.all(blocks.map((raw) => { const block = raw as { title: string; description?: string; category: TimeBlockCategory; startsAt: string; endsAt: string; itemId?: string | null }; const start = new Date(block.startsAt); const end = new Date(block.endsAt); return api("/api/planner", { method: "POST", body: JSON.stringify({ ...block, startsAt: `${day}T${String(start.getHours()).padStart(2, "0")}:${String(start.getMinutes()).padStart(2, "0")}:00.000Z`, endsAt: `${day}T${String(end.getHours()).padStart(2, "0")}:${String(end.getMinutes()).padStart(2, "0")}:00.000Z`, recurrence: null }) }); })); notify("Template applicato senza modificare i blocchi presenti."); onApplied(); } catch (error) { notify(errorMessage(error)); } }
 return <section className="planner-panel"><div className="panel-title"><Sparkles size={16}/><h2>Template del giorno</h2></div>{templates.length ? templates.map((template) => <button className="template-row" key={template.id} onClick={() => apply(template)}><span>{template.name}</span><Copy size={14}/></button>) : <p className="muted">Salva una giornata dal menu di un blocco per riutilizzarla.</p>}</section>; }
function BlockEditor({ block, day, seed, onClose, onSaved, onFocus }: { block: TimeBlockSummary | null; day: string; seed: { itemId?: string; title?: string } | null; onClose: () => void; onSaved: () => void; onFocus: (block: TimeBlockSummary) => void }) { const { notify } = useWorkspace(); const [title, setTitle] = useState(block?.title ?? seed?.title ?? ""); const [startsAt, setStartsAt] = useState(block ? inputValue(block.startsAt) : dateAt(day, 9)); const [endsAt, setEndsAt] = useState(block ? inputValue(block.endsAt) : dateAt(day, 10)); const [category, setCategory] = useState<TimeBlockCategory>(block?.category ?? "OTHER"); const [description, setDescription] = useState(block?.description ?? ""); const [itemId, setItemId] = useState(block?.itemId ?? seed?.itemId ?? ""); const [recurring, setRecurring] = useState(Boolean(block?.recurrence)); const [saving, setSaving] = useState(false);
 async function save() { setSaving(true); try { await api(`/api/planner${block ? `/${block.id.split(":")[0]}` : ""}`, { method: block ? "PATCH" : "POST", body: JSON.stringify({ title, startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString(), category, description, itemId: itemId || null, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "Europe/Rome", recurrence: recurring ? { frequency: "WEEKLY", weekdays: [new Date(startsAt).getDay()] } : null }) }); notify("Blocco salvato."); onSaved(); } catch (error) { notify(errorMessage(error)); } finally { setSaving(false); } }
 async function remove() { if (!block || !window.confirm(`Eliminare “${block.title}”?`)) return; try { await api(`/api/planner/${block.id.split(":")[0]}`, { method: "DELETE" }); notify("Blocco eliminato."); onSaved(); } catch (error) { notify(errorMessage(error)); } }
 return <Modal open onOpenChange={(open) => !open && onClose()} title={block ? "Modifica blocco" : "Nuovo blocco"} description="Il blocco pianifica tempo; l’attività collegata resta indipendente." wide><div className="block-form"><label>Titolo<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Es. Scrivere la proposta"/></label><div className="form-columns"><label>Inizio<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)}/></label><label>Fine<input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)}/></label></div><label>Categoria<select value={category} onChange={(event) => setCategory(event.target.value as TimeBlockCategory)}>{Object.entries(categoryLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Collega un elemento Synapse <span className="field-hint">ID opzionale: puoi copiare l’ID dalla pagina dell’elemento.</span><input value={itemId} onChange={(event) => setItemId(event.target.value)} placeholder="ID di nota, attività o progetto"/></label><label>Descrizione<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} placeholder="Contesto o intenzione per questa sessione"/></label><label className="recurrence-toggle"><input type="checkbox" checked={recurring} onChange={(event) => setRecurring(event.target.checked)}/><span>Ripeti ogni settimana nello stesso giorno</span></label></div><div className="dialog-footer">{block && <><button className="button button-ghost" onClick={() => onFocus(block)}><Focus size={15}/>Focus</button><button className="button button-danger" onClick={remove}><Trash2 size={15}/>Elimina</button></>}<button className="button button-secondary" onClick={onClose}>Annulla</button><button className="button button-primary" disabled={saving} onClick={save}><Save size={15}/>{saving ? "Salvataggio…" : "Salva"}</button></div></Modal>; }
function FocusMode({ block, onClose, onSaved }: { block: TimeBlockSummary; onClose: () => void; onSaved: () => void }) { const { notify } = useWorkspace(); const [running, setRunning] = useState(block.status === "IN_PROGRESS"); async function toggle(action: "start" | "stop" | "complete") { try { await api(`/api/planner/${block.id.split(":")[0]}/focus`, { method: "POST", body: JSON.stringify({ action }) }); setRunning(action === "start"); notify(action === "complete" ? "Blocco completato." : action === "start" ? "Focus avviato." : "Focus in pausa."); onSaved(); } catch (error) { notify(errorMessage(error)); } } return <Modal open onOpenChange={(open) => !open && onClose()} title="Modalità Focus" description="Il tempo registrato resta salvato anche se chiudi o aggiorni la pagina."><div className="focus-card"><Clock3 size={28}/><h3>{block.title}</h3><p>{formatTime(block.startsAt)}–{formatTime(block.endsAt)} · {categoryLabels[block.category]}</p>{block.item && <Link href={getItemHref(block.item)}>Apri {block.item.title}</Link>}<div className="focus-actions">{running ? <button className="button button-secondary" onClick={() => toggle("stop")}><Pause size={16}/>Pausa</button> : <button className="button button-primary" onClick={() => toggle("start")}><Play size={16}/>Avvia</button>}<button className="button button-secondary" onClick={() => toggle("complete")}><Check size={16}/>Termina</button></div></div></Modal>; }
function hours(minutes: number) { if (!minutes) return "0 min"; const h = Math.floor(minutes / 60); const m = minutes % 60; return `${h ? `${h} h` : ""}${h && m ? " " : ""}${m ? `${m} min` : ""}`; }
